name: OpenShift Deployer
description: OpenShift deployer with route verification or penetration testing
branding:
  icon: package
  color: blue

inputs:
  ### Required
  file:
    description: Template file (e.g. frontend/openshift.deploy.yml)
    required: true
  oc_namespace:
    description: OpenShift namespace (e.g. abc123-dev)
    required: true
  oc_server:
    description: OpenShift server (e.g. https://api.silver.devops.gov.bc.ca:6443)
    required: true
  oc_token:
    description: OpenShift access token
    required: true
  overwrite:
    description: Replace existing objects/artifacts? (true|false)
    required: true

  ### Typical / recommended
  parameters:
    description: Template parameters/variables to pass (e.g. -p ZONE=...)
  penetration_test:
    description: Run a ZAProxy penetration test against any routes? [true/false]
  penetration_test_fail:
    description: Allow ZAProxy alerts to fail the workflow? [true/false]
    default: "false"
  triggers:
    description: Paths used to trigger a build; e.g. ('./backend/', './frontend/)
    default: "."
  verification_path:
    description: Sets the health endpoint to be used during check stage, does not require the '/' at the begining
    default: ""
  verification_retry_attempts:
    description: Number of times to attempt deployment verification
    default: "3"
  verification_retry_seconds:
    description: Seconds to wait between deployment verification attempts
    default: "10"

  ### Usually a bad idea / not recommended
  repository:
    default: ${{ github.repository }}
    description: Optionally, specify a different repo to clone

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}

    # Process variables and inputs
    - id: vars
      shell: bash
      run: |
        # Inputs and variables

        # Bug - OpenShift hates images with capitals in org/repo names
        REPO=${{ inputs.repository }}
        if [[ $o != ${o,,} ]]; then 
          echo -e "An OpenShift bug prevents capital letters in repo names.\n"
          echo -e "Please handle that using the `repository` parameter.\n"
          exit 1
        fi

        # Process template, consuming variables/parameters
        TEMPLATE="$(oc process -f ${{ inputs.file }} ${{ inputs.parameters }} --local)"

        # ImageStream, DeploymentConfig and Route Host from template
        DC=$(jq -rn "${TEMPLATE} | .items[] | select(.kind==\"DeploymentConfig\").metadata.name //empty")
        IS=$(jq -rn "${TEMPLATE} | .items[] | select(.kind==\"ImageStream\").metadata.name //empty")
        ROUTE_HOST=$(jq -rn "${TEMPLATE} | .items[] | select(.kind==\"Route\").spec.host //empty")

        # Route path from inputs or template (inputs.verification_path takes priority)
        ROUTE_PATH=${{ inputs.verification_path }}
        [ ! -z "${ROUTE_PATH}" ]|| \
          ROUTE_PATH=$(jq -rn "${TEMPLATE} | .items[] | select(.kind==\"Route\").spec.path //empty")

        # Build URL from route and path, but only if ROUTE_HOST is populated
        [ -z "${ROUTE_HOST}" ]|| URL_HOST_PATH="${ROUTE_HOST}/${ROUTE_PATH}"

        echo imageStream=${IS} >> $GITHUB_OUTPUT
        echo deploymentConfig=${DC} >> $GITHUB_OUTPUT

        # Removes any double slashles, e.g. inputs.verification_path
        echo url=${URL_HOST_PATH} | sed 's // / g' >> $GITHUB_OUTPUT

        # Triggers
        TRIGGERS=${{ inputs.triggers }}
        git fetch origin "${{ github.event.repository.default_branch }}"
        while read -r check; do
          for t in "${TRIGGERS[@]}"; do
            if [[ "${check}" =~ "${t}" ]]; then
                echo -e "Triggered: ${t}\n --> ${check}"
                echo "triggered=true" >> $GITHUB_OUTPUT
                exit 0
            fi
          done
        done < <(git diff origin/"${{ github.event.repository.default_branch }}" --name-only)

        echo "Triggers not matched"
        echo "triggered=false" >> $GITHUB_OUTPUT

    - name: Deploy
      if: steps.vars.outputs.triggered
      shell: bash
      run: |
        # Allow pipefail, since we could be catching oc create errors
        set +o pipefail

        # Login to OpenShift (NOTE: project command is a safeguard)
        oc login --token=${{ inputs.oc_token }} --server=${{ inputs.oc_server }}
        oc project ${{ inputs.oc_namespace }}

        # Clean previous image, if any
        IFS=" " read -ra IS <<< "${{ steps.vars.outputs.imageStream }}"
        for i in "${IS[@]}"
        do
          [ ! $(oc get is -o name | grep ^imagestream.image.openshift.io/${i}$) ]|| oc delete is/${i}
        done

        # Apply (overwrites) or create (does not overwrite) using processed template
        TEMPLATE="$(oc process -f ${{ inputs.file }} ${{ inputs.parameters }} --local)"
        if [ "${{ inputs.overwrite }}" == "true" ]; then
          oc apply -f - <<< "${TEMPLATE}"
        else
          # Suppress AlreadyExists errors and expected failure
          oc create -f - 2>&1 <<< "${TEMPLATE}" | sed 's/.*: //'
        fi

        # Follow any active rollouts (see deploymentconfigs)
        DC=${{ steps.vars.outputs.deploymentConfig }}
        [ -z "${DC}" ]|| oc rollout status dc/${DC} -w

    - name: Route Verification
      if: steps.vars.outputs.url && steps.vars.outputs.triggered && inputs.penetration_test
      shell: bash
      run: |
        # Route verification

        # Check for URL (route + path)
        URL_HOST_PATH=${{ steps.vars.outputs.url }}
        if [ -z "${URL_HOST_PATH}" ]; then
          echo -e "\nNo route found. Skipping."
          exit 0
        fi
        echo -e "\nURL: ${URL_HOST_PATH}"

        # Curl and verify
        TRIES="${{ inputs.verification_retry_attempts }}"
        SECONDS="${{ inputs.verification_retry_seconds }}"
        for (( i=0; i<"${TRIES}"; i++ )); do
          HTTP_CODE=$(curl -Lso /dev/null -w "%{http_code}" "${URL_HOST_PATH}")
          if [ "${HTTP_CODE}" -eq 200 ]; then
            echo -e "Deployment successful!"
            exit 0
          fi
          echo -e "HTTP_CODE:${HTTP_CODE}, Try: #${i}"
          sleep "${SECONDS}"
        done
        echo -e "\nRoute verification failed"
        exit 1

    - name: Penetration Test
      if: steps.vars.outputs.url && steps.vars.outputs.triggered && inputs.penetration_test
      uses: zaproxy/action-full-scan@v0.4.0
      with:
        target: https://${{ steps.vars.outputs.url }}
        cmd_options: "-a"
        fail_action: ${{ inputs.penetration_test_fail }}
        allow_issue_writing: false

    # Action repo needs to be present for cleanup/tests
    - name: Checkout to make sure action.yml is present (tests)
      if: ${{ github.repository }} != ${{ inputs.repository }}
      uses: actions/checkout@v3
