apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAME
    description: Module name
    value: action-deployer-openshift
  - name: COMPONENT
    description: Component name
    value: frontend
  - name: ZONE
    description: Deployment zone, e.g. pr-### or prod
    required: true
  - name: DOMAIN
    value: apps.silver.devops.gov.bc.ca
  - name: CPU_REQUEST
    value: "25m"
  - name: MEMORY_REQUEST
    value: "50Mi"
  - name: CPU_LIMIT
    value: "75m"
  - name: MEMORY_LIMIT
    value: "150Mi"
  - name: LOG_LEVEL
    description: Caddy logging level DEBUG, INFO, WARN, ERROR, PANIC, and FATAL (https://github.com/caddyserver/caddy/blob/master/logging.go)
    value: "info"
  - name: CRON_MINUTES
    description: Random number, 0-60, for scheduling cronjobs
    from: "[0-5]{1}[0-9]{1}"
    generate: expression
  - name: RANDOM_EXPRESSION
    description: Random expression to make sure deployments update
    from: "[a-zA-Z0-9]{32}"
    generate: expression
objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        app: ${NAME}-${ZONE}
        component: ${COMPONENT}
      name: "${NAME}-${ZONE}-${COMPONENT}"
    spec:
      replicas: 1
      selector:
        matchLabels:
          deployment: "${NAME}-${ZONE}-${COMPONENT}"
      strategy:
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: ${NAME}-${ZONE}
            component: ${COMPONENT}
            deployment: "${NAME}-${ZONE}-${COMPONENT}"
        spec:
          containers:
            - image: "ghcr.io/bcgov/quickstart-openshift/frontend:latest"
              securityContext:
                capabilities:
                  add: ["NET_BIND_SERVICE"]
              imagePullPolicy: Always
              name: "${NAME}"
              env:
                - name: BACKEND_URL
                  value: "https://${NAME}-${ZONE}-backend.${DOMAIN}:443"
                - name: LOG_LEVEL
                  value: "${LOG_LEVEL}"
                - name: RANDOM_EXPRESSION
                  value: ${RANDOM_EXPRESSION}
              ports:
                - containerPort: 3000
                  protocol: TCP
              resources:
                requests:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
                limits:
                  cpu: "${CPU_LIMIT}"
                  memory: "${MEMORY_LIMIT}"
              readinessProbe:
                httpGet:
                  path: /health
                  port: 3001
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 2
                timeoutSeconds: 2
                successThreshold: 1
                failureThreshold: 30
              livenessProbe:
                successThreshold: 1
                failureThreshold: 3
                httpGet:
                  path: /health
                  port: 3001
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 30
                timeoutSeconds: 5
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}-${ZONE}
        component: ${COMPONENT}
      name: "${NAME}-${ZONE}-${COMPONENT}"
    spec:
      ports:
        - name: 3000-tcp
          protocol: TCP
          port: 80
          targetPort: 3000
      selector:
        deployment: "${NAME}-${ZONE}-${COMPONENT}"
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: ${NAME}-${ZONE}
        component: ${COMPONENT}
      name: "${NAME}-${ZONE}-${COMPONENT}"
    spec:
      host: "${NAME}-${ZONE}-${COMPONENT}.${DOMAIN}"
      port:
        targetPort: 3000-tcp
      to:
        kind: Service
        name: "${NAME}-${ZONE}-${COMPONENT}"
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
  - apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      labels:
        app: ${NAME}-${ZONE}
        component: ${COMPONENT}
      name: "${NAME}-${ZONE}-${COMPONENT}"
    spec:
      scaleTargetRef:
        apiVersion: apps.openshift.io/v1
        kind: Deployment
        name: "${NAME}-${ZONE}-${COMPONENT}"
      minReplicas: 1
      maxReplicas: 2
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 100
  - kind: CronJob
    apiVersion: batch/v1
    metadata:
      labels:
        app: ${NAME}-${ZONE}
        component: ${COMPONENT}
      name: ${NAME}-${ZONE}-cronjob
    spec:
      concurrencyPolicy: Replace
      schedule: "${CRON_MINUTES} 9 * * * " # Run daily at 9:xx AM UTC
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                app: ${NAME}-${ZONE}
                component: ${COMPONENT}
                cronjob: ${NAME}-${ZONE}-cronjob
            spec:
              restartPolicy: OnFailure
              containers:
                - name: ${NAME}-${ZONE}-cronjob
                  image: "ghcr.io/bcgov/quickstart-openshift/frontend:latest"
                  imagePullPolicy: Always
                  args: ["bash -c 'whoami'"]
                  resources:
                    requests:
                      cpu: ${CPU_REQUEST}
                      memory: ${MEMORY_REQUEST}
